# Generated by Django 3.2.5 on 2021-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_prediksidatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
