# Generated by Django 3.2.5 on 2021-08-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dataapimodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataapimodel',
            options={'managed': False},
        ),
    ]
